# Generated by Django 4.2.4 on 2023-08-12 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('isActive', models.BooleanField()),
            ],
        ),
        migrations.RemoveField(
            model_name='course',
            name='isUpdate',
        ),
    ]
