# Generated by Django 4.2.4 on 2023-08-12 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_category_remove_course_isupdate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='isActive',
        ),
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.CharField(default='name', max_length=50),
        ),
    ]
