# Generated by Django 4.2.4 on 2023-08-15 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_course_category_alter_course_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.CharField(db_index=True, default='', max_length=50, unique=True),
        ),
    ]
